# The server to fetch assets from
# Current available options are US and CN
server = "CN"

# The path to cache resource versions at
versions_path = "cache/versions.json"

# The path to cache asset hashes at
hashes_path = "cache/hashes.json"

# If set to false, the files at versions_path and hashes_path will not be updated
update_cache = true

# The output directory for extracted assets
output_dir = "assets"

# Optional; an asset will only be processed if its path contains one of the paths in this list
path_whitelist = [
    "arts/building/buffs/buff_icon_hub.ab",         # Facility icons
    "spritepack/building_ui_buff_skills_h1_0.ab",   # Base skill icons
    "spritepack/ui_char_avatar",                    # Operator avatars (E0, E2, skin)
    "arts/charportraits",                           # Operator portraits (E0, E2, skin)
    "chararts",                                     # Operator artworks (E0, E2); includes Spine assets
    "skinpack",                                     # Operator artworks (skin); includes Spine assets
    "ui_equip_big_img_hub_h1",                      # Equipment modules
]