[fetch-settings]
server = "CN"
details_path = "details.json"
hashes_path = "hashes.json"
force_fetch = false
output_dir = "assets"
update_cache = true

[unpack-settings]
input_dir = "assets"
output_dir = "results"